# Site wide configuration

title:            Pmint
locale:           vi-VN
url:              http://pmint93.github.io
source:           .
destination:      ./../pmint93.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Thanh Pham
  avatar: pmint93.jpg
  bio: "."
  email: phamminhthanh69@gmail.com
  disqus-shortname: pmint93
  twitter: pmint93
  facebook: pmint93
  google:
    plus: 103799953412679091715
    analytics: UA-57630353-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: pmint93
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: pmint93
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: pmint93
  soundcloud: thanh-pham-minh

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
